services:

    #
    # EventDispatchers
    #
    elcodi.event_dispatcher.cart_line_coupon:
        class: Elcodi\Component\CartLineCoupon\EventDispatcher\CartLineCouponEventDispatcher
        parent: elcodi.event_dispatcher.abstract

    elcodi.event_dispatcher.order_line_coupon:
        class: Elcodi\Component\CartLineCoupon\EventDispatcher\OrderLineCouponEventDispatcher
        parent: elcodi.event_dispatcher.abstract
