services:

    #
    # Event Listeners
    #
    #    elcodi.event_listener.refresh_coupons:
    #        class: Elcodi\Component\CartLineCoupon\EventListener\RefreshCouponsEventListener
    #        arguments:
    #            - @elcodi.manager.coupon
    #            - @elcodi.manager.cart_line_coupon
    #            - @elcodi.wrapper.currency
    #            - @elcodi.converter.currency
    #            - @elcodi.event_dispatcher.cart_line_coupon
    #        tags:
    #            - { name: kernel.event_listener, event: cart.onload, method: refreshCartLineCoupons, priority: 0 }
    #            - { name: kernel.event_listener, event: cart.onload, method: refreshCouponAmount, priority: -32 }
    #
    elcodi.event_listener.automatic_coupons:
        class: Elcodi\Component\CartLineCoupon\EventListener\AutomaticCouponApplicatorEventListener
        arguments:
            - @elcodi.manager.cart_line_coupon
            - @elcodi.repository.coupon
        tags:
            - { name: kernel.event_listener, event: cart.onload, method: tryAutomaticCoupons, priority: -16 }

    elcodi.event_listener.avoid_coupon_duplicates:
        class: Elcodi\Component\CartLineCoupon\EventListener\AvoidDuplicatesEventListener
        arguments:
            - @elcodi.repository.cart_line_coupon
        tags:
            - { name: kernel.event_listener, event: cart_line_coupon.onapply, method: checkDuplicates, priority: 16 }

    elcodi.event_listener.stackable_coupon:
        class: Elcodi\Component\CartLineCoupon\EventListener\StackableCouponEventListener
        arguments:
            - @elcodi.repository.cart_line_coupon
        tags:
            - { name: kernel.event_listener, event: cart_line_coupon.onapply, method: checkStackableCoupon, priority: 16 }

    elcodi.event_listener.cart_line_coupon_checker:
        class: Elcodi\Component\CartLineCoupon\EventListener\CheckCartLineCouponEventListener
        arguments:
            - @elcodi.event_dispatcher.cart_line_coupon
        tags:
            - { name: kernel.event_listener, event: cart_line_coupon.onapply, method: checkCoupon, priority: 16 }

    elcodi.event_listener.cart_line_coupon_manager:
        class: Elcodi\Component\CartLineCoupon\EventListener\CartLineCouponManagerEventListener
        arguments:
            - @elcodi.object_manager.cart_line_coupon
            - @elcodi.factory.cart_line_coupon
        tags:
            - { name: kernel.event_listener, event: cart_line_coupon.onapply, method: onCartLineCouponApply, priority: 0 }
            - { name: kernel.event_listener, event: cart_line_coupon.onremove, method: onCartLineCouponRemove, priority: 0 }

    elcodi.event_listener.coupon_checker:
        class: Elcodi\Component\CartLineCoupon\EventListener\CheckCouponEventListener
        arguments:
            - @elcodi.manager.coupon
        tags:
            - { name: kernel.event_listener, event: cart_line_coupon.oncheck, method: checkCoupon, priority: 32 }

    elcodi.event_listener.check_minimum_price:
        class: Elcodi\Component\CartLineCoupon\EventListener\MinimumPriceCouponEventListener
        arguments:
            - @elcodi.converter.currency
        tags:
            - { name: kernel.event_listener, event: cart_line_coupon.oncheck, method: checkMinimumPrice, priority: 0 }

    elcodi.event_listener.check_product_in_cart_line:
        class: Elcodi\Component\CartLineCoupon\EventListener\ProductInCartLineCouponEventListener
        tags:
            - { name: kernel.event_listener, event: cart_line_coupon.oncheck, method: checkProductInCartLine, priority: 0 }

    elcodi.event_listener.check_rules:
        class: Elcodi\Component\CartLineCoupon\EventListener\CheckRulesEventListener
        arguments:
            - @elcodi.manager.cart_coupon_rule
        tags:
            - { name: kernel.event_listener, event: cart_line_coupon.oncheck, method: checkCoupon, priority: -16 }

    elcodi.event_listener.convert_to_order_line:
        class: Elcodi\Component\CartLineCoupon\EventListener\ConvertToOrderLineCouponsEventListener
        arguments:
            - @elcodi.event_dispatcher.order_line_coupon
            - @elcodi.manager.cart_line_coupon
            - @elcodi.manager.order_line_coupon
            - @elcodi.object_manager.order_line_coupon
        tags:
            - { name: kernel.event_listener, event: orderi_line.oncreated, method: convertCouponToOrderLine, priority: -16 }

    elcodi.event_listener.order_coupon_manager:
        class: Elcodi\Component\CartLineCoupon\EventListener\OrderLineCouponManagerEventListener
        arguments:
            - @elcodi.object_manager.order_line_coupon
            - @elcodi.event_dispatcher.coupon
            - @elcodi.factory.order_line_coupon
        tags:
            - { name: kernel.event_listener, event: order_line_coupon.onapply, method: convertToOrderLineCoupons, priority: 0 }
