services:

    #
    # Factories
    #

    #
    # Factory for entity cart_line_coupon
    #
    elcodi.factory.cart_line_coupon:
        class: Elcodi\Component\CartLineCoupon\Factory\CartLineCouponFactory
        parent: elcodi.factory.abstract.purchasable
        calls:
            - [setEntityNamespace, ["%elcodi.entity.cart_line_coupon.class%"]]

    #
    # Factory for entity order_line_coupon
    #
    elcodi.factory.order_line_coupon:
        class: Elcodi\Component\CartLineCoupon\Factory\OrderLineCouponFactory
        calls:
            - [setEntityNamespace, ["%elcodi.entity.order_line_coupon.class%"]]
