services:

    #
    # Services
    #
    elcodi.manager.cart_line_coupon:
        class: Elcodi\Component\CartLineCoupon\Services\CartLineCouponManager
        arguments:
            - @elcodi.event_dispatcher.cart_line_coupon
            - @elcodi.manager.coupon
            - @elcodi.repository.coupon
            - @elcodi.repository.cart_line_coupon

    elcodi.manager.order_line_coupon:
        class: Elcodi\Component\CartLineCoupon\Services\OrderLineCouponManager
        arguments:
            - @elcodi.repository.order_line_coupon

    elcodi.manager.cart_line_coupon_rule:
        class: Elcodi\Component\CartLineCoupon\Services\CartLineCouponRuleManager
        arguments:
            - @elcodi.manager.rule
