Elcodi\Component\CartLineCoupon\Entity\CartLineCoupon:
    type: entity
    repositoryClass: Elcodi\Component\CartLineCoupon\Repository\CartLineCouponRepository
    table: cart_line_coupon
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    manyToOne:
        cartLine:
            targetEntity: Elcodi\Component\Cart\Entity\Interfaces\CartLineInterface
            joinColumn:
                name: cart_line_id
                referencedColumnName: id
        coupon:
            targetEntity: Elcodi\Component\Coupon\Entity\Interfaces\CouponInterface
            fetch: EAGER
            joinColumn:
                name: coupon_id
                referencedColumnName: id
