Elcodi\Component\CartLineCoupon\Entity\OrderLineCoupon:
    type: entity
    repositoryClass: Elcodi\Component\CartLineCoupon\Repository\OrderLineCouponRepository
    table: order_line_coupon
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        amount:
            column: amount
            type: integer
        code:
            column: code
            type: string
            length: 255
            nullable: false
        name:
            column: name
            type: string
            length: 255
            nullable: false
    manyToOne:
        orderLine:
            targetEntity: Elcodi\Component\Cart\Entity\Interfaces\OrderLineInterface
            joinColumn:
                name: order_line_id
                referencedColumnName: id
        coupon:
            targetEntity: Elcodi\Component\Coupon\Entity\Interfaces\CouponInterface
            fetch: EAGER
            joinColumn:
                name: coupon_id
                referencedColumnName: id
        amountCurrency:
            targetEntity: Elcodi\Component\Currency\Entity\Interfaces\CurrencyInterface
            fetch: EAGER
            joinColumn:
                 name: amount_currency_iso
                 referencedColumnName: iso
                 nullable: true
